# Generated by Django 6.0.4 on 2026-05-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps.teams', '0004_alter_team_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Supervisor grade (0-100)', max_digits=5, null=True)),
                ('committee1_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Committee Doctor 1 grade (0-100)', max_digits=5, null=True)),
                ('committee2_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Committee Doctor 2 grade (0-100)', max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Final grade (auto-calculated)', max_digits=5, null=True)),
                ('letter_grade', models.CharField(blank=True, editable=False, help_text='Letter grade (auto-calculated)', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grades', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps.grades', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('team',), name='unique_team_grade')],
            },
        ),
    ]
