# Generated by Django 4.2.13 on 2026-04-10 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Proposal', 'Proposal'), ('Midterm', 'Midterm'), ('Final', 'Final')], max_length=20)),
                ('chief_grade', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('examiner_one_grade', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('examiner_two_grade', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_grade', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('archived_file', models.FileField(blank=True, null=True, upload_to='grading_archives/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_reports', to='teams.team')),
            ],
            options={
                'db_table': 'grading_gradingreport',
                'ordering': ['-created_at'],
                'unique_together': {('team', 'phase')},
            },
        ),
    ]
