# Generated by Django 4.2.13 on 2026-04-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('active', 'Active'), ('complete', 'Complete'), ('disbanded', 'Disbanded')], default='forming', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('academic_year', models.CharField(default='2025-2026', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teams', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='member_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams_team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='teams.team')),
            ],
            options={
                'db_table': 'teams_membershiprequest',
                'unique_together': {('team', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dates', to='teams.team')),
            ],
            options={
                'db_table': 'teams_examdate',
                'unique_together': {('team', 'date')},
            },
        ),
    ]
