# Generated by Django 4.2.13 on 2026-05-29 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='no_voters',
            field=models.ManyToManyField(blank=True, related_name='voted_no_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='yes_voters',
            field=models.ManyToManyField(blank=True, related_name='voted_yes_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
