# Generated by Django 6.0.4 on 2026-05-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps.teams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_schedules', to='teams.team')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
