# Generated by Django 4.2.13 on 2026-04-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('supervisor_request', 'Supervisor Request'), ('supervisor_assigned', 'Supervisor Assigned'), ('request_rejected', 'Request Rejected'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_booked', 'Meeting Booked'), ('grade_published', 'Grade Published'), ('report_saved', 'Report Saved'), ('file_uploaded', 'File Uploaded'), ('supervisor_comment', 'Supervisor Comment'), ('join_request', 'Join Request'), ('join_approved', 'Join Approved'), ('join_rejected', 'Join Rejected'), ('general', 'General')], default='general', max_length=40)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
